services:
  - type: web
    name: ride-andhra-unified-db
    env: node
    region: singapore
    plan: free
    branch: master
    repo: https://github.com/Praween-em/Ride_andhra_unified_db
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://ride_andhra_unified_db_user:FxtuobcOgCkrNzPGXMDSVkYYvJsCpdlA@dpg-d529ca75r7bs73a1c530-a/ride_andhra_unified_db
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: ride-andhra-db
    databaseName: Ride_andhra_unified_db
    user: ride_andhra_user
    plan: free
    region: singapore
